### ISSUE TITLE
HA new Quality scale

### ISSUE THREAD

**Issue by catsmanac** [pyenphase/pyenphase#192]
HA redefined the quality scale. Posting an initial assessment of current status here, and closing the now obsolete #141.

- for bronze:
  - <s>There's some work in docs, some additions and some rearrangements to regroup are add required headings.</s>
  - [test-before-setup](https://developers.home-assistant.io/docs/core/integration-quality-scale/rules/test-before-setup) not 100% clear. We return 2 of the 3 required stats, but also UpdateFailed.
- for silver
  - <s>Again some docs requirements to fulfill</s>
  - <s>Need to add[ `PARALLEL_UPDATES = 1`](https://developers.home-assistant.io/docs/core/integration-quality-scale/rules/parallel-updates/) for each platform (if 1 is the right choice) </s>
- for Gold
  - Again some docs requirements to fulfill
  - exception and icon translation may need some attention and maybe some entity-category changes for the CT status
- for Platinum
  - all met
 
Edit 4-12-2024, updated status with results of https://github.com/home-assistant/home-assistant.io/pull/36128
Edit 5-12-2024, updated with results of https://github.com/home-assistant/core/pull/132373 for PARALLEL_UPDATES

```yaml
rules:
  # Bronze
  action-setup: done
  appropriate-polling: done
  brands: done
  common-modules: done
  config-flow-test-coverage: done
  config-flow: done
  dependency-transparency: done
  docs-actions: 
    status: done
    comment: pending https://github.com/home-assistant/home-assistant.io/pull/36128
  docs-high-level-description:
    status: done
    comment: pending https://github.com/home-assistant/home-assistant.io/pull/36128
  docs-installation-instructions:
    status: done
    comment: pending https://github.com/home-assistant/home-assistant.io/pull/36128
  docs-removal-instructions:
    status: done
    comment: pending https://github.com/home-assistant/home-assistant.io/pull/36128
  entity-event-setup:
    status: done
    comment: no events used.
  entity-unique-id: done
  has-entity-name: done
  runtime-data: done
  test-before-configure: done
  test-before-setup: done
  unique-config-entry: done

  # Silver
  action-exceptions:
    status: todo
    coment: |
      no integration specific services used. Entity actions through standard
      number, select and switch platform actions. pyenphase library will
      raise on errors in function implementations.
  config-entry-unloading:
    status: done
    comment: |
      implements async_unload_entry in _init_.py which cancels a daily scheduled job created at load
      registers entry.async_on_unload to for at reload.
  docs-configuration-parameters:
    status: done
    comment: pending https://github.com/home-assistant/home-assistant.io/pull/36128
  docs-installation-parameters: 
    status: done
    comment: pending https://github.com/home-assistant/home-assistant.io/pull/36128
  entity-unavailable: done
  integration-owner: done
  log-when-unavailable: done
  parallel-updates:
    status: done
    comment: pending https://github.com/home-assistant/core/pull/132373
  reauthentication-flow: done
  test-coverage: done

  # Gold
  devices: done
  diagnostics: done
  discovery-update-info: done
  discovery: done
  docs-data-update:
    status: done
    comment: pending https://github.com/home-assistant/home-assistant.io/pull/36128
  docs-examples:
    status: todo
    comment: add blue-print examples, if any
  docs-known-limitations: todo
  docs-supported-devices: done
  docs-supported-functions: todo
  docs-troubleshooting: done
  docs-use-cases: todo
  dynamic-devices:
    status: todo
    comment: |
      inverter devices are removed !?
  entity-category:
    status: todo
    comment: |
      check for ct sensors.
  entity-device-class: done
  entity-disabled-by-default: done
  entity-translations: done
  exception-translations: todo
  icon-translations: todo
  reconfiguration-flow: done
  repair-issues: todo
  stale-devices:
    status: done
    comment: |
      devices like pv inverters may move to other/new envoy and will be created
      with same serialnumber id and name to retain their hisory so no automatic
      remove is implemented, but rather the async_remove_config_entry_device

  # Platinum
  async-dependency: done
  inject-websession: done
  strict-typing: done
```
